CREATE TYPE user_role AS ENUM ('PATIENT', 'DOCTOR', 'ADMIN');
CREATE TYPE biological_sex AS ENUM ('MALE', 'FEMALE', 'OTHER');
CREATE TYPE address_type AS ENUM ('HOME', 'CLINIC', 'BILLING');
CREATE TYPE consent_status AS ENUM ('GRANTED', 'REVOKED', 'EXPIRED');
CREATE TYPE appointment_type AS ENUM ('ONLINE', 'WALKIN', 'TELEHEALTH');
CREATE TYPE appointment_status AS ENUM ('BOOKED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW');
CREATE TYPE notification_channel AS ENUM ('WHATSAPP', 'SMS', 'PUSH', 'EMAIL');
CREATE TYPE notification_status AS ENUM ('PENDING', 'SENT', 'DELIVERED', 'FAILED');
