global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    platform: reejuven8
    env: dev

scrape_configs:
  - job_name: api-gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: identity-abha-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8081']

  - job_name: health-data-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8082']

  - job_name: ninemo-clinical-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8084']

  - job_name: notification-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8085']

  - job_name: ninemo-community-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8086']
